CREATE table BOOK
(
BookId NUMBER(2) PRIMARY KEY,
Title Char(10),
PublisherName Char(20)
);

CREATE table BOOK_AUTHORS
(
BookId NUMBER(2),
AuthorName VARCHAR(10),
CONSTRAINT xyz PRIMARY KEY (BookId,AuthorName)
);

CREATE table PUBLISHER
(
pubName CHAR(20) PRIMARY KEY,
Address VARCHAR2(20),
Phone NUMBER (10)
);

CREATE table LIBRARY_BRANCH
(
BranchId NUMBER(4) PRIMARY KEY,
BranchName VARCHAR2(20),
Address VARCHAR2(10)
);

CREATE table BOOK_COPIES
(
BookId NUMBER(2),
BranchId NUMBER(4) ,
No_Of_Copies NUMBER (4) ,
CONSTRAINT xy PRIMARY KEY (BookId,BranchId)
);

CREATE table BOOK_LOANS
(

BookId NUMBER(2),
BranchId NUMBER(4),
CardNo Number(3),
CONSTRAINT x PRIMARY KEY (BookId,BranchId,CardNo)

);


CREATE table BORROWER
(
CardNo Number(3) PRIMARY KEY ,
Name VARCHAR2(15),
Phone NUMBER (10),
Address VARCHAR2(10)
);

ALTER table BOOK
ADD CONSTRAINT pName FOREIGN KEY (PublisherName) REFERENCES PUBLISHER(pubName);

ALTER table BOOK_AUTHORS
ADD CONSTRAINT authBookId FOREIGN KEY (BookId) REFERENCES BOOK(BookId);

ALTER table BOOK_COPIES
ADD CONSTRAINT copBookId FOREIGN KEY (BookId) REFERENCES BOOK(BookId);

ALTER table BOOK_COPIES
ADD CONSTRAINT copBranchId FOREIGN KEY (BranchId) REFERENCES LIBRARY_BRANCH(BranchId);

ALTER table BOOK_LOANS
ADD CONSTRAINT loanBookId FOREIGN KEY (BookId) REFERENCES BOOK(BookId);

ALTER table BOOK_LOANS
ADD CONSTRAINT loanBranchId FOREIGN KEY (BranchId) REFERENCES LIBRARY_BRANCH(BranchId);

ALTER table BOOK_LOANS
ADD CONSTRAINT loanCardNo FOREIGN KEY (CardNo) REFERENCES BORROWER(CardNo);
