// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Q3;

/************************************************************/
/**
 * 
 */
public class in_patient extends patient {
	/**
	 * 
	 */
	public void purchase_med() {
	}
};
