// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Q3;

/************************************************************/
/**
 * 
 */
public class patient extends person {
	/**
	 * 
	 */
	public void Book_an_appointment() {
	}
};
