package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, November 17, 2019 7:17:42 PM PKT
*/

public interface HelloOperations 
{
  String EqOfMotion (String v0, String t, String a);
  void shutdown ();
} // interface HelloOperations
